# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20160718_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='front_cam',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='release_data',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.FloatField(default=None),
        ),
    ]
