# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20160730_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='front_cam',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='release_data',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='screen_size',
        ),
    ]
